[package]
name = "nns-csv-trends"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-rc.7"
rust_decimal = "1.18.0"